eapp/urls.py
from .views import index
from django.urls import include, path
from . import views
from .views import SellerLoginView
from rest_framework.routers import DefaultRouter
from .views import CustomerViewSet, SellerViewSet, ProductViewSet, CategoryViewSet, SubcategoryViewSet, CartViewSet, OrderViewSet, OrderItemViewSet, PurchaseOrderViewSet, PurchaseOrderItemViewSet, AddressViewSet


# Create a router and register our viewsets
router = DefaultRouter()
router.register(r'customers', CustomerViewSet)
router.register(r'sellers', SellerViewSet)
router.register(r'products', ProductViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'subcategories', SubcategoryViewSet)
router.register(r'carts', CartViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'orderitems', OrderItemViewSet)
router.register(r'purchaseorders', PurchaseOrderViewSet)
router.register(r'purchaseorderitems', PurchaseOrderItemViewSet)
router.register(r'addresses', AddressViewSet)

urlpatterns = [
    path('',views.index,name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('change_password/', views.change_password, name='change_password'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/<uidb64>/<token>/', views.reset_password, name='reset_password'),
    path('logout/', views.user_logout, name='logout'),
    path('edit_customer/', views.edit_customer, name='edit_customer'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('address/', views.address_list, name='address_list'),
    path('address/add/', views.address_create, name='address_create'),
    path('address/edit/<int:pk>/', views.address_edit, name='address_edit'),
    path('address/delete/<int:pk>/', views.address_delete, name='address_delete'),
    path("cart/", views.cart, name="cart"),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/increase/<int:cart_item_id>/', views.increase_quantity, name='increase_quantity'),
    path('cart/decrease/<int:cart_item_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('delete_item_in_cart/<int:id>/', views.delete_item_in_cart, name='delete_item_in_cart'),
    path('checkouts/', views.checkout, name='checkouts'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('product_list/',views.product_list,name='product_list'),
    path('search/', views.search_results, name='search_results'),
    path('category/<int:category_id>/', views.category_products, name='category_products'),
    path('subcategory/<int:subcategory_id>/', views.subcategory_products, name='subcategory_products'),
    path('create_purchase_order/', views.CreatePurchaseOrderView.as_view(), name='create_purchase_order'),
    path('seller_purchase_orders/<int:purchase_order_id>/', views.purchase_order_details, name='purchase_order_details'),
    path('seller/purchase_orders/', views.seller_purchase_orders, name='seller_purchase_orders'),
    path('seller_login/', SellerLoginView.as_view(), name='seller_login'),
    path('reject_purchase_order/<int:purchase_order_id>/', views.reject_purchase_order, name='reject_purchase_order'),

    path('api/', include(router.urls)), 


]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
# If DEBUG is True, serve static files using Django
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

eapp/models.py
from decimal import Decimal
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MinLengthValidator


class Address(models.Model):
    recepient_name = models.CharField(max_length=100, null=True)
    recepient_contact = models.CharField(max_length=20, null=True)
    address_line1 = models.CharField(max_length=255)
    address_line2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.address_line1}, {self.address_line2}, {self.city}, {self.state} - {self.postal_code}"    

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    customer_name = models.CharField(max_length=100)
    contact_number = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    role = models.CharField(max_length=50, default='customer')

    def __str__(self):
        return self.customer_name
   
    

class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone_no = models.CharField(max_length=12, unique=True, validators=[MinLengthValidator(10)])
    address = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

class Category(models.Model):
    category_name = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.category_name

class Subcategory(models.Model):
    subcategory_name = models.CharField(max_length=100)
    parent_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.subcategory_name

class Product(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_1 = models.ImageField(upload_to='product_images/')
    image_2 = models.ImageField(upload_to='product_images/', blank=True, null=True)
    quantity_in_stock = models.PositiveIntegerField(default=0)
    reorder_level = models.PositiveIntegerField(default=0)
    cost= models.DecimalField(max_digits=10,decimal_places=2,default=100)

    def __str__(self):
        return self.name



class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    def sub_total(self):
        return int(self.product.price) * int(self.quantity)

    def __str__(self):
        return f"Cart - Customer: {self.customer.customer_name} - Product: {self.product.name} - Qty: {self.quantity}"
    
    
class Order(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Processing', 'Processing'),
        ('Shipped/Dispatched', 'Shipped/Dispatched'),
        ('Delivered', 'Delivered'),
    ]
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    order_date = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')

    def total_price(self):
        return sum(item.total_price() for item in self.orderitem_set.all())

    def __str__(self):
        return f"Order - Customer: {self.customer.customer_name} - Status: {self.status}"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def total_price(self):
        return self.product.price * self.quantity

    def __str__(self):
        return f"Order Item - Order: {self.order.id} - Product: {self.product.name} - Qty: {self.quantity}"
    

# Define the PurchaseOrder model
class PurchaseOrder(models.Model):
    TotalAmount = models.DecimalField(max_digits=20, decimal_places=2)
    PurchaseOrderDate = models.DateField()
    Status = models.CharField(max_length=250, blank=True)
    ExpectedDeliveryDate = models.DateField(blank=True, null=True)
    Seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    seller_message = models.TextField(blank=True)
    
    def _str_(self):
        return f"Purchase Order {self.id}"

class PurchaseOrderItem(models.Model):
    Quantity = models.IntegerField()
    Product = models.ForeignKey(Product, on_delete=models.CASCADE)
    PurchaseOrder = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)
    PurchaseUnitPrice = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    TotalAmount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def save(self, *args, **kwargs):
        # Calculate total amount before saving
        if self.Quantity is not None and self.PurchaseUnitPrice is not None:
            self.TotalAmount = Decimal(self.Quantity) * Decimal(self.PurchaseUnitPrice)
        super().save(*args, **kwargs)

    def _str_(self):
        return f"Purchase Order Item {self.id}"

eapp/forms.py
from django import forms
from .models import Address

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['recepient_name', 'recepient_contact', 'address_line1', 'address_line2', 'city', 'state', 'postal_code']
        widgets = {
            'recepient_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Recipient Name'}),
            'recepient_contact': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Recipient Contact'}),
            'address_line1': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address Line 1'}),
            'address_line2': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address Line 2'}),
            'city': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City'}),
            'state': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'State'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Postal Code'}),
        }

eapp/templates/bill_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Bill</title>
    <style>
        /* Add your CSS styles here */
        /* Example styles: */
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Order Bill</h1>
    <p>Order ID: {{ order.id }}</p>
    <p>Order Date: {{ order.order_date }}</p>
    <table>
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>Total Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.orderitem_set.all %}
            <tr>
                <td>{{ item.product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>${{ item.product.price }}</td>
                <td>${{ item.total_price }}</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">Total</td>
                <td>${{ order.total_price }}</td>
            </tr>
        </tfoot>
    </table>
</body>
</html>

eapp/templates/cart.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <div class="hero-wrap hero-bread" style="background-image: url('../static/images/bg_6.jpg');">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	
            <h1 class="mb-0 bread">My Cart</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
								<th>Images</th>
								<th>Product</th>
								<th>Unit Price</th>
								<th>Quantity</th>
								<th>Total</th>
								<th>Remove</th>
						      </tr>
						    </thead>
						    <tbody>
								{% for item in cart_items %}
						      <tr class="text-center">
                                <td class="product-remove">
                                    <button type="submit" formaction="{% url 'delete_item_in_cart' item.product.id %}" name="product_id" value="{{ item.product.id }}"><i class="ion-ios-close"></i></button>
                                </td>
						        <td class="image-prod"><div class="img" style="background-image: url('{{ item.product.image_1.url }}');"></div></td>
						        
						        <td class="product-name">
						        	<h3>{{ item.product.name }}</h3>
						        </td>
						        
						        <td class="price">${{ item.product.price }}</td>
						        
								<td class="product-quantity">
									<div class="cart-quantity">
										<a href="{% url 'decrease_quantity' item.id %}" class="quantity-button">-</a>
										<input type="text" name="quantity" value="{{ item.quantity }}" class="quantity-input" readonly>
										<a href="{% url 'increase_quantity' item.id %}" class="quantity-button">+</a>
									</div>
								</td> 
						        
						        <td class="total">₹{{ item.sub_total|floatformat:2 }}</td>
						      </tr><!-- END TR-->
							  {% endfor %}
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
    		<div class="row justify-content-start">
    			<div class="col col-lg-5 col-md-6 mt-5 cart-wrap ftco-animate">
    				<div class="cart-total mb-3">
    					<h3>Cart Totals</h3>
    					<p class="d-flex">
    						<span>Subtotal</span>
    						<span>${{ total_price }}</span>
    					</p>
    					<hr>
    					<p class="d-flex total-price">
    						<span>Total</span>
    						<span>${{ total_price }}</span>
    					</p>
    				</div>
					{% if cart_items %}
    				<p class="text-center"><a class="btn btn-primary py-3 px-4" href="{% url 'checkouts' %}">Proceed to checkout</a></p>
					
                {% else %}
                <p style="font-size: large; color: brown; font-weight: bold;">Your cart is empty. Please add items to proceed.</p>
                {% endif %}
    			</div>
    		</div>
			</div>
		</section>
		{% endblock %}		

eapp/templates/order_confirmation_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Confirmation</title>
    <style>
        /* Add your CSS styles here */
        /* Example styles: */
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
        img {
            max-width: 100px;
            max-height: 100px;
        }
    </style>
</head>
<body>
    <h1>Order Confirmation</h1>
    <p>Thank you for your order!</p>
    <p>Your order details:</p>
    <p>Delivery Address: {{ order.address }}</p>
    <table>
        <thead>
            <tr>
                <th>Product Image</th>
                <th>Product Name</th>
                <th>Quantity</th>
                <th>Subtotal</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.orderitem_set.all %}
            <tr>
                <td><img src="{{ item.product.image_1.url }}" alt="{{ item.product.name }}"></td>
                <td>{{ item.product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>${{ item.total_price }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p>Total: ${{ order.total_price }}</p>
    <p>We will process your order shortly.</p>
</body>
</html>

eapp/templates/order_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid" style="padding: 50px; background-color: #f5f5f5; margin-top: 100px;">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="card shadow-lg border-0 rounded-lg">
        <div class="card-header" style="background-color: #0f0f0e;">
          <h3 class="text-center font-weight-light my-4" style="color: rgb(245, 239, 239);">Orders</h3>
        </div>
        <div class="card-body">
          {% for order in orders %}
          <a href="{% url 'order_detail' order.id %}">
          <div class="card mb-3" style="background-color: #ffffff; border: 1px solid #ced4da;">
            <div class="card-header" style="background-color: #ffffff; color: rgb(243, 235, 235);">
              <h5 class="mb-0">Order ID: {{ order.id }}</h5>
            </div>
            <div class="card-body">
              <p class="card-text">Order Date: {{ order.order_date }}</p>
              <p class="card-text">Order Status: {{ order.status }}</p>
              <p class="card-text">Order Address: {{ order.address }}</p>
            </div>
          </div>
        </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function toggleOrderItems(orderId) {
    var orderItems = document.getElementById('orderItems' + orderId);
    if (orderItems.style.display === 'none') {
      orderItems.style.display = 'block';
    } else {
      orderItems.style.display = 'none';
    }
  }
</script>

{% endblock %}

eapp/templates/product_list.html
{% extends 'base.html' %}

{% block content %} 

{% load static %}

<div
  class="hero-wrap hero-bread"
  style="background-image: url('static/images/bg_6.jpg')"
>
  <div class="container">
    <div
      class="row no-gutters slider-text align-items-center justify-content-center"
    >
      <div class="col-md-9 ftco-animate text-center">
        <p class="breadcrumbs">
          <span class="mr-2"><a href="index.html">LUSH</a></span>
          
        </p>
        <h1 class="mb-0 bread">Shop</h1>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-lg-10 order-md-last">
        <div class="row">
			{% for product in products %}
          <div class="col-sm-12 col-md-12 col-lg-4 ftco-animate d-flex">
            <div class="product d-flex flex-column">
              <a href="{% url 'product_detail' product.id %}" class="img-prod"
                ><img
                  class="img-fluid"
                  src="{{ product.image_1.url }}"
                  alt="Colorlib Template"
                />
                <div class="overlay"></div>
              </a>
              <div class="text py-3 pb-4 px-3">
                <div class="d-flex">
                  <div class="cat">
                    <span>{{ product.subcategory }}</span>
                  </div>
                  <div class="rating">
                    <p class="text-right mb-0">
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                    </p>
                  </div>
                </div>
                <h3><a href="#">{{ product.name }}</a></h3>
                <div class="pricing">
                  <p class="price"><span>${{ product.price }}</span></p>
                </div>
                <p class="bottom-area d-flex px-3">
					<form id="add-to-cart-form" action="{% url 'add_to_cart' %}" method="post">
						{% csrf_token %}
						<input type="hidden" name="product_id" value="{{ product.id }}">
						<input type="hidden" name="quantity" value="1">
						<button type="submit" id="cart-button" ><a href="#" class="add-to-cart text-center py-2 mr-1"><span>Add to cart <i class="ion-ios-add ml-1"></i></span></a></button>
					</form>
				</p>
              </div>
            </div>
          </div>
		  {% endfor %}
        </div>
      </div>

      <div class="col-md-4 col-lg-2">
        <div class="sidebar">
          <div class="sidebar-box-2">
            <h2 class="heading">Categories</h2>
            <div class="fancy-collapse-panel">
              <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                {% for category in categories %}
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                          <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">{{ category.category_name }}</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            <ul>
                              {% for subcategory in category.subcategory_set.all %}
                              <li><a href="{% url 'subcategory_products' subcategory.id %}">{{ subcategory.subcategory_name }}</a></li>
                              {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                {% endfor %}
             </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

eapp/templates/search_results.html
{% extends 'base.html' %} {% block content %} {% load static %}

<div
  class="hero-wrap hero-bread"
  style="background-image: url('images/bg_6.jpg')"
>
  <div class="container">
    <div
      class="row no-gutters slider-text align-items-center justify-content-center"
    >
      <div class="col-md-9 ftco-animate text-center">
        <p class="breadcrumbs">
          <span class="mr-2"><a href="index.html">Home</a></span>
          <span>Shop</span>
        </p>
        <h1 class="mb-0 bread">Shop</h1>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-lg-10 order-md-last">
        <div class="row">
			{% for product in products %}
          <div class="col-sm-12 col-md-12 col-lg-4 ftco-animate d-flex">
            <div class="product d-flex flex-column">
              <a href="{% url 'product_detail' product.id %}" class="img-prod"
                ><img
                  class="img-fluid"
                  src="{{ product.image_1.url }}"
                  alt="Colorlib Template"
                />
                <div class="overlay"></div>
              </a>
              <div class="text py-3 pb-4 px-3">
                <div class="d-flex">
                  <div class="cat">
                    <span>{{ product.subcategory }}</span>
                  </div>
                  <div class="rating">
                    <p class="text-right mb-0">
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                    </p>
                  </div>
                </div>
                <h3><a href="#">{{ product.name }}</a></h3>
                <div class="pricing">
                  <p class="price"><span>${{ product.price }}</span></p>
                </div>
                <p class="bottom-area d-flex px-3">
					<form id="add-to-cart-form" action="{% url 'add_to_cart' %}" method="post">
						{% csrf_token %}
						<input type="hidden" name="product_id" value="{{ product.id }}">
						<input type="hidden" name="quantity" value="1">
						<button type="submit" id="cart-button" ><a href="#" class="add-to-cart text-center py-2 mr-1"><span>Add to cart <i class="ion-ios-add ml-1"></i></span></a></button>
					</form>
				</p>
              </div>
            </div>
          </div>
		  {% endfor %}
        </div>
      </div>

      <div class="col-md-4 col-lg-2">
        <div class="sidebar">
          <div class="sidebar-box-2">
            <h2 class="heading">Categories</h2>
            <div class="fancy-collapse-panel">
              <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                {% for category in categories %}
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                          <a href="{% url 'category_products' category.id %}"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">{{ category.category_name }}
                            </a></a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            <ul>
                              {% for subcategory in category.subcategory_set.all %}
                              <li><a href="{% url 'subcategory_products' subcategory.id %}">{{ subcategory.subcategory_name }}</a></li>
                              {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                {% endfor %}
             </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

eapp/templates/subcategory_products.html
{% extends 'base.html' %} {% block content %} {% load static %}

<div
  class="hero-wrap hero-bread"
  style="background-image: url('images/bg_6.jpg')"
>
  <div class="container">
    <div
      class="row no-gutters slider-text align-items-center justify-content-center"
    >
      <div class="col-md-9 ftco-animate text-center">
        <p class="breadcrumbs">
          <span class="mr-2"><a href="index.html">Home</a></span>
          <span>Shop</span>
        </p>
        <h1 class="mb-0 bread">Shop</h1>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-lg-10 order-md-last">
        <div class="row">
			{% for product in products %}
          <div class="col-sm-12 col-md-12 col-lg-4 ftco-animate d-flex">
            <div class="product d-flex flex-column">
              <a href="{% url 'product_detail' product.id %}" class="img-prod"
                ><img
                  class="img-fluid"
                  src="{{ product.image_1.url }}"
                  alt="Colorlib Template"
                />
                <div class="overlay"></div>
              </a>
              <div class="text py-3 pb-4 px-3">
                <div class="d-flex">
                  <div class="cat">
                    <span>{{ product.subcategory }}</span>
                  </div>
                  <div class="rating">
                    <p class="text-right mb-0">
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                      <a href="#"><span class="ion-ios-star-outline"></span></a>
                    </p>
                  </div>
                </div>
                <h3><a href="#">{{ product.name }}</a></h3>
                <div class="pricing">
                  <p class="price"><span>${{ product.price }}</span></p>
                </div>
                <p class="bottom-area d-flex px-3">
					<form id="add-to-cart-form" action="{% url 'add_to_cart' %}" method="post">
						{% csrf_token %}
						<input type="hidden" name="product_id" value="{{ product.id }}">
						<input type="hidden" name="quantity" value="1">
						<button type="submit" id="cart-button" ><a href="#" class="add-to-cart text-center py-2 mr-1"><span>Add to cart <i class="ion-ios-add ml-1"></i></span></a></button>
					</form>
				</p>
              </div>
            </div>
          </div>
		  {% endfor %}
        </div>
      </div>

      <div class="col-md-4 col-lg-2">
        <div class="sidebar">
          <div class="sidebar-box-2">
            <h2 class="heading">Categories</h2>
            <div class="fancy-collapse-panel">
              <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                {% for category in categories %}
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                          <a href="{% url 'category_products' category.id %}"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">{{ category.category_name }}
                            </a></a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            <ul>
                              {% for subcategory in category.subcategory_set.all %}
                              <li><a href="{% url 'subcategory_products' subcategory.id %}">{{ subcategory.subcategory_name }}</a></li>
                              {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                {% endfor %}
             </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}